### ISSUE TITLE
Plugin gives error, Command failed

### ISSUE THREAD

**Issue by ghost** [Delgan/qml-format#9]
Formatting of 'Binning.qml' failed (1): 'Command failed: /usr/lib64/qt6/bin/qmlformat -i /home/preiter/git_repos/stgcore_developer/UnisonCore/Binning-6enrgm6x-formatting-tmp.qml '.

When I execute this command from the VSCode terminal...

preiter@usmilpreiter-al91> cp /home/preiter/git_repos/stgcore_developer/UnisonCore/Binning.qml  /home/preiter/git_repos/stgcore_developer/UnisonCore/Binning-6enrgm6x-formatting-tmp.qml
preiter@usmilpreiter-al91> /usr/lib64/qt6/bin/qmlformat -i /home/preiter/git_repos/stgcore_developer/UnisonCore/Binning-6enrgm6x-formatting-tmp.qml
preiter@usmilpreiter-al91> echo  $status
0

This is with VSCode version 1.95.1 
Running on AlmaLinux 9.1
Qt version 6.6

**Comment by Delgan** [comment]
Hi @peter-reiter.

Can you please try to manually run `qmlformat -i Binning.qml` on the source file directly without any `cp` operation? Does it work?

At first glance I don't have an explanation for the problem you are experiencing. I should try adding the command output to the VS Code error message, maybe that could help.

**Comment by ghost** [comment]
Yes, I have tried running qmlformat on the original source file and it works.

I think that seeing the full output of the qmlformat command would be very helpful.

**Comment by Delgan** [comment]
I've just published a new version that adds logs to the "Output" panel of VS Code.

![output](https://github.com/user-attachments/assets/ebf37f8d-63bb-4753-987b-3e71e04160b2)

Can you please update the _QML Format_ extension to v1.1.0 and check what's in the logs?

Though, usually the `stderr` is already part of the error message, so I'm not sure we'll be getting any new insights.

**Comment by ghost** [comment]
Unfortunately no new information appeared...

![image](https://github.com/user-attachments/assets/ce2a4e9a-ce2d-4135-82cb-6218b7f0cc02)

**Comment by Delgan** [comment]
One last suggestion maybe: can you add `--verbose` to the command arguments in the _QML Format_ extension settings please? Then, check again the output of the extension.

![extra arguments](https://github.com/user-attachments/assets/49f0edbb-8ca9-4553-8ec1-cd828a7ec16a)

[Here](https://codebrowser.dev/qt6/qtdeclarative/tools/qmlformat/qmlformat.cpp.html) are the sources of the `qmlformat` command, maybe we'll find out where it fails.

Another interesting test would be to replace the `qmlformat` command in the extension settings with a random command like `echo`. This would validate that the problem comes from the execution of the command and not from the creation of the temporary file.

There's also something curious in your screenshot, which is that it seems to take ~1.5 second before the command fails. That's a surprisingly long time. But I don't know what could explain this behavior.

Unfortunately, I'm running out of ideas. I tested the extension on Almalinux and it worked. Could be related to file permissions, but I'm not sure. Is there anything unusual in your dev setup? Any remote environment or using NFS mounts perhaps?

The only solution otherwise would be to try debugging the extension on your own, and contribute your fix to this repo. As I'm unable to reproduce your problem, I'm afraid I can't help any further.

**Comment by ghost** [comment]
Great suggestions.

adding the verbose parameter gave no additional information.

I replaced the qmlformat command with a python script that dumped the parameters and that worked fine.

Then I replaced it with this python script...

```
#! /usr/bin/python3
import sys
import subprocess

def main():
    subprocess.run(["/usr/bin/qmlformat-qt6", "-i", sys.argv[2]])

if __name__ == "__main__":
    main()
```

This successfully formatted the file.  

I am working on a virtual machine on a server, so could be something weird about the file system. I have no clue what's going on, but at least I have a workaround. Thanks for the help.

**Comment by Delgan** [comment]
Thanks for the update. Glad you figured out a workaround.

I note that in your Python script, you use `/usr/bin/qmlformat-qt6`, whereas in the error you reported, it seems `/usr/lib64/qt6/bin/qmlformat` is used.

Is there any difference between? Have you tried configuring `/usr/bin/qmlformat-qt6` as the command to execute, in the extension settings?

**Comment by ghost** [comment]
Nope, those are the same command at two different locations.

**Comment by Delgan** [comment]
Ok. Very weird bug. It'will remain unexplained then.

Thanks for your patience.
